SELECT * FROM dual; 
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER scott CASCADE;
CREATE USER scott IDENTIFIED BY tiger;
GRANT CONNECT,RESOURCE TO scott;
GRANT CREATE VIEW TO scott;
GRANT unlimited TABLESPACE TO scott;